name: Build Windows (Manual)

env:
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  LLVM_VERSION: "15.0.6"

on:
  workflow_dispatch:

jobs:
  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10

  build-windows:
    name: x86_64-pc-windows-msvc (windows-2022)
    runs-on: windows-2022
    strategy:
      fail-fast: false
    steps:
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Checkout source code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        submodules: recursive

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@1a3da29f56261a1e1f937ec88f0856a9b8321d7e # v1
      with:
        version: ${{ env.LLVM_VERSION }}

    - name: Setup vcpkg with Github Actions binary cache
      uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11
      with:
        vcpkgDirectory: C:\vcpkg
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

    - name: Install vcpkg dependencies
      env:
        VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
      run: |
        if ! $VCPKG_ROOT/vcpkg \
          install \
          --triplet x64-windows-static \
          --x-install-root="$VCPKG_ROOT/installed"; then
          find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
            echo "$_1:"
            echo "======"
            cat "$_1"
            echo "======"
            echo ""
          done
          exit 1
        fi
      shell: bash

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc
        components: ''

    - name: Show version information (Rust, cargo)
      shell: bash
      run: |
        rustup -V
        rustup toolchain list
        rustup default
        cargo -V
        rustc -V

    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

    - name: Build
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
      with:
        command: build
        args: --locked --release --target=x86_64-pc-windows-msvc

    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: rustdesk-windows-x86_64
        path: target/x86_64-pc-windows-msvc/release/
        if-no-files-found: error
